name: CommandBin
version: 4.0
author: CainFoool
main: org.caindonaghey.commandbin.CommandBin
commands:
   tp:
       description: 'Teleport to a player, teleport a player to co-ordinates, teleport a player to another player'
       usage: /tp [player] <player/xyz>
   tphere:
       description: 'Teleport a player to your current location'
       usage: /tphere [player]
   spawn:
       description: 'Teleport you or another player to current world spawn location'
       usage: /spawn <player>
   setspawn:
       description: 'Set the current world spawn location for players'
       usage: /setspawn
   bolt:
       description: 'Strike a player with lightning'
       usage: /bolt [player]
   setxp:
       description: 'Set a players experience level'
       usage: /setxp <player> [level]